name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t hardddyy/flask-app:latest .

      - name: Push Docker image
        run: docker push hardddyy/flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies including conntrack, crictl, and CNI plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl conntrack
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          curl -LO "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-amd64.tar.gz"
          sudo tar zxvf crictl-v1.32.0-linux-amd64.tar.gz -C /usr/local/bin
          sudo ln -s /usr/local/bin/crictl /usr/bin/crictl
          # Download and install CNI plugins
          curl -LO "https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz"
          sudo mkdir -p /opt/cni/bin
          sudo tar -xzvf cni-plugins-linux-amd64-v1.1.1.tgz -C /opt/cni/bin
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/
      - name: Start Minikube with Docker driver as non-root user
        run: |
          sudo -i -u $USER bash <<EOF
          minikube start --driver=docker
          minikube addons enable ingress
          EOF
      - name: Set up kubectl context
        run: |
          sudo -i -u $USER bash <<EOF
          minikube update-context
          EOF
      - name: Apply Kubernetes deployment
        run: |
          sudo -i -u $USER bash <<EOF
          kubectl apply -f $(pwd)/deployment.yaml
          EOF
      - name: Apply Kubernetes service
        run: |
          sudo -i -u $USER bash <<EOF
          kubectl apply -f $(pwd)/service.yaml
          EOF
      - name: Wait for pod readiness
        run: |
          sudo -i -u $USER bash <<'EOF'
          kubectl wait --for=condition=ready pod -l app=flask-app --timeout=120s
          EOF
      - name: Log deployment status
        run: |
          sudo -i -u $USER bash <<EOF
          kubectl get nodes
          kubectl get pods --all-namespaces
          kubectl get services --all-namespaces
          kubectl get deployments --all-namespaces
          EOF
      - name: Describe deployment
        run: |
          sudo -i -u $USER bash <<EOF
          kubectl describe deployment flask-app
          EOF
      - name: Describe service
        run: |
          sudo -i -u $USER bash <<EOF
          kubectl describe svc flask-app-service
          EOF
      - name: Check pod status and labels
        run: |
          sudo -i -u $USER bash <<EOF
          kubectl get pods -l app=flask-app -o wide
          kubectl get pod -l app=flask-app --show-labels
          EOF
      - name: Fetch node internal IP
        run: |
          NODE_IP=$(kubectl get nodes -o wide | grep -m 1 -oP '(?<=\s)\d{1,3}(\.\d{1,3}){3}(?=\s)')
          echo "Node IP: $NODE_IP"

          if [[ $NODE_IP == *"."* ]]; then
            echo "Fetching from Node IP: http://$NODE_IP:32188"
            curl http://$NODE_IP:32188 || echo "Flask app not reachable"
          else
            echo "Invalid Node IP address: $NODE_IP"
          fi
      - name: Notify Slack or log
        if: failure()
        run: echo "Deployment failed!"
