name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Flask
        run: pip install -r requirements.txt

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t hardddyy/flask-app:latest .

      - name: Push Docker image
        run: docker push hardddyy/flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies including conntrack and crictl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl conntrack
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          curl -LO "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-amd64.tar.gz"
          sudo tar zxvf crictl-v1.32.0-linux-amd64.tar.gz -C /usr/local/bin
          sudo ln -s /usr/local/bin/crictl /usr/bin/crictl[_{{{CITATION{{{_1{install: cannot stat 'bin/cri-dockerd': No such file or directory](https://github.com/Mirantis/cri-dockerd/issues/94)

      - name: Install cri-dockerd
        run: |
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          sudo make cri-dockerd
          sudo install -o root -g root -m 0755 cri-dockerd /usr/local/bin/cri-dockerd
          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.service
          sudo systemctl start cri-docker.service

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube addons enable ingress

      - name: Set up kubectl context
        run: |
          minikube update-context

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl apply -f k8s-service.yaml
          kubectl rollout status deployment/flask-app

      - name: Log deployment status
        run: |
          kubectl get nodes
          kubectl get pods --all-namespaces
          kubectl get services --all-namespaces
          kubectl get deployments --all-namespaces

      - name: Describe pod
        run: kubectl describe pod -l app=flask-app

      - name: Describe deployment
        run: kubectl describe deployment flask-app

      - name: Log events
        run: kubectl get events --sort-by=.metadata.creationTimestamp --namespace default

      - name: Check pod logs
        run: |
          POD_NAME=$(kubectl get pods -l app=flask-app -o jsonpath="{.items[0].metadata.name}" --namespace default || echo "NoPod")
          if [[ "$POD_NAME" != "NoPod" ]]; then
            kubectl logs $POD_NAME
          else
            echo "No pods available to log."
          fi

      - name: Check Flask app response
        run: |
          POD_NAME=$(kubectl get pods -l app=flask-app -o jsonpath="{.items[0].metadata.name}" --namespace default || echo "NoPod")
          if [[ "$POD_NAME" != "NoPod" ]]; then
            kubectl port-forward $POD_NAME 5000:5000 &
            sleep 10
            curl http://localhost:5000 || echo "Flask app not reachable"
          else
            echo "No pods available for port-forwarding."
          fi

      - name: Notify Slack or log
        if: failure()
        run: echo "Deployment failed!"
